<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page {
            margin: 110px 30px 65px 30px;
        }

        * {
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #374151;
            font-size: 11px;
            line-height: 1.5;
        }

        header {
            position: fixed;
            top: -90px;
            left: 0;
            right: 0;
            height: 70px;
        }

        footer {
            position: fixed;
            bottom: -45px;
            left: 0;
            right: 0;
            height: 30px;
            font-size: 10px;
            color: #6B7280;
        }

        .page-number:after {
            content: counter(page);
        }

        .page-total:after {
            content: counter(pages);
        }

        .watermark {
            position: fixed;
            top: 38%;
            left: 20%;
            font-size: 85px;
            color: #EEF2FF;
            transform: rotate(-35deg);
            z-index: -1000;
            font-weight: bold;
        }

        .layout-table {
            width: 100%;
            border-collapse: collapse;
            border: none;
        }

        .layout-table td {
            border: none;
            vertical-align: middle;
            padding: 0;
        }

        .summary-box {
            padding: 12px;
            border-radius: 6px;
        }

        .summary-box b {
            font-size: 11px;
            color: #374151;
        }

        .summary-box .value {
            font-size: 14px;
            font-weight: bold;
            margin-top: 6px;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        .report-table thead {
            display: table-header-group;
        }

        .report-table tr {
            page-break-inside: avoid;
        }

        .report-table th {
            background: #6C99FA;
            color: white;
            border: 1px solid #D1D5DB;
            padding: 10px 6px;
            text-align: center;
            font-size: 11px;
            font-weight: bold;
        }

        .report-table td {
            border: 1px solid #E5E7EB;
            padding: 8px 6px;
            font-size: 10px;
            vertical-align: middle;
            word-wrap: break-word;
        }

        .report-table tbody tr:nth-child(even) {
            background: #F8FAFC;
        }

        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-left { text-align: left; }

        .badge {
            display: inline-block;
            color: white;
            font-size: 9px;
            padding: 3px 8px;
            border-radius: 20px;
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
        }

        .badge-income { background: #16A34A; }
        .badge-expense { background: #DC2626; }
        .badge-transfer { background: #2563EB; }

        .total-row td {
            background: #EFF6FF;
            font-weight: bold;
            font-size: 11px;
        }

        .empty {
            padding: 30px;
            text-align: center;
            color: #6B7280;
            font-size: 12px;
        }
    </style>
</head>
<body>

<div class="watermark">BUDGETIN</div>

<header>
    <table class="layout-table">
        <tr>
            <td width="70">
                <img src="{{ public_path('images/logo/logo-icon.png') }}" width="48">
            </td>
            <td>
                <div style="font-size: 24px; font-weight: bold; color: #2563EB; line-height: 1.1;">Budgetin</div>
                <div style="font-size: 12px; color: #6B7280; margin-top: 2px;">Financial Tracker Report</div>
            </td>
            <td align="right" style="font-size: 11px; color: #6B7280; line-height: 1.4;">
                <strong>Generated :</strong><br>
                {{ now()->format('d F Y H:i') }}
            </td>
        </tr>
    </table>
    <hr style="border: none; border-top: 2px solid #6C99FA; margin-top: 12px; margin-bottom: 0;">
</header>

<footer>
    <table class="layout-table" style="border-top: 1px solid #E5E7EB; padding-top: 8px;">
        <tr>
            <td>Generated by Budgetin</td>
            <td align="center" style="font-weight: bold; color: #9CA3AF; letter-spacing: 1px;">CONFIDENTIAL</td>
            <td align="right">
                Page <span class="page-number"></span> of <span class="page-total"></span>
            </td>
        </tr>
    </table>
</footer>

<table class="layout-table" style="margin-top: 10px; margin-bottom: 15px; font-size: 11px;">
    <tr>
        <td width="30%">
            <strong>Report Type :</strong> {{ ucfirst($type) }}
        </td>
        <td width="30%">
            <strong>Filter :</strong> {{ ucfirst($filter) }}
        </td>
        <td width="40%">
            <strong>Period :</strong> 
            @if($filter == 'day')
                {{ \Carbon\Carbon::parse($selectedDate)->format('d F Y') }}
            @elseif($filter == 'month')
                {{ \Carbon\Carbon::parse($selectedMonth.'-01')->format('F Y') }}
            @else
                All Period
            @endif
        </td>
    </tr>
</table>

<table class="layout-table" style="margin-bottom: 25px;">
    <tr>
        <td width="23.5%">
            <div class="summary-box" style="background: #DCFCE7;">
                <b>Total Income</b>
                <div class="value" style="color: #16A34A;">IDR {{ number_format($totalIncome, 0, ',', '.') }}</div>
            </div>
        </td>
        <td width="2%"></td>
        <td width="23.5%">
            <div class="summary-box" style="background: #FEE2E2;">
                <b>Total Expense</b>
                <div class="value" style="color: #DC2626;">IDR {{ number_format($totalExpense, 0, ',', '.') }}</div>
            </div>
        </td>
        <td width="2%"></td>
        <td width="23.5%">
            <div class="summary-box" style="background: #DBEAFE;">
                <b>Total Transfer</b>
                <div class="value" style="color: #2563EB;">IDR {{ number_format($totalTransfer, 0, ',', '.') }}</div>
            </div>
        </td>
        <td width="2%"></td>
        <td width="23.5%">
            <div class="summary-box" style="background: #F3F4F6;">
                <b>Total Data</b>
                <div class="value" style="color: #4B5563;">{{ $reports->count() }} Transactions</div>
            </div>
        </td>
    </tr>
</table>

<table class="report-table">
    <thead>
        <tr>
            <th width="4%">No</th>
            <th width="11%">Date</th>
            <th width="11%">Type</th>
            <th width="13%">Category</th>
            <th width="20%">Title</th>
            <th width="13%">Amount</th>
            <th width="14%">Account</th>
            <th width="14%">Description</th>
        </tr>
    </thead>
    <tbody>
        @forelse($reports as $index => $report)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td class="text-center">{{ \Carbon\Carbon::parse($report->date)->format('d M Y') }}</td>
                <td class="text-center">
                    @if($report->type == "income")
                        <span class="badge badge-income">Income</span>
                    @elseif($report->type == "expense")
                        <span class="badge badge-expense">Expense</span>
                    @else
                        <span class="badge badge-transfer">Transfer</span>
                    @endif
                </td>
                <td>{{ $report->category->name ?? '-' }}</td>
                <td>{{ $report->title ?? '-' }}</td>
                <td class="text-right">IDR {{ number_format($report->amount, 0, ',', '.') }}</td>
                <td>
                    @if($report->type == "transfer")
                        {{ $report->fromAccount->name ?? '-' }} &rarr; {{ $report->toAccount->name ?? '-' }}
                    @else
                        {{ $report->fromAccount->name ?? '-' }}
                    @endif
                </td>
                <td>{{ $report->description ?: '-' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="8" class="empty">No transaction found.</td>
            </tr>
        @endforelse

        @if($reports->count())
            <tr class="total-row">
                <td colspan="5">Total Transaction Amount</td>
                <td class="text-right">IDR {{ number_format($reports->sum('amount'), 0, ',', '.') }}</td>
                <td colspan="2" class="text-center">{{ $reports->count() }} Transaction(s)</td>
            </tr>
        @endif
    </tbody>
</table>

</body>
</html>